### ISSUE TITLE
unable to install plugin.

### ISSUE THREAD

**Issue by omegagx** [pablodav/nagios_sql#1]
When I try to install this on my Nagios XI box running CentOS 6, I get the following error:

```
/usr/bin/pip install git+https://github.com/pablodav/nagios_sql.git
Collecting git+https://github.com/pablodav/nagios_sql.git
  Cloning https://github.com/pablodav/nagios_sql.git to /tmp/pip-yLyXTv-build
Unpacking objects: 100% (38/38), done.
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-yLyXTv-build/setup.py", line 17, in <module>
        exec(open('src/version.py').read())
      File "<string>", line 5
        **__version__ = '0.5.1'
                             ^
    SyntaxError: invalid syntax**

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-yLyXTv-build/
```

Any ideas what could be causing this?

**Comment by pablodav** [comment]
I haven't done any test in python2, only python3 was used during the build of it. 

You can try https://www.softwarecollections.org/en/ and install python3

then use 

```
python3 -m pip install nagios_sql 
```

Or also:

```
pip3 install nagios_sql 
```

same to install from github. 

python2 support could take some time to get, so will keep this issue open until you get it working (with python3 or 2 if no luck to have python3).

**Comment by pablodav** [comment]
For what I see in the documentation: 

https://www.softwarecollections.org/en/scls/rhscl/rh-python34/

The command for installed python will be:

```
easy_install nagios_sql
```

I don't know if they provide pip by default, but worked for me on ubuntu 14.04 with both easy_install and pip.

**Comment by omegagx** [comment]
This is on CentOS 6.
I installed python3.6 and pip3.6 on it in /usr/local and that worked - the plugin installed successfully.

However, just FYI, trying your suggestion with the native system 2.6 python failed:

[root@local]# easy_install nagios_sql
Searching for nagios_sql
Reading https://pypi.python.org/simple/nagios_sql/
Downloading https://pypi.python.org/packages/69/dc/10ba9cb9178f59162dc92beb172b1cbb5f68c013c1d8d40ff3f566667d42/nagios_sql-0.5.1.tar.gz#md5=7ba2d47d358577033847ff33d35f532d
Best match: nagios-sql 0.5.1
Processing nagios_sql-0.5.1.tar.gz
Writing /tmp/easy_install-AjEE1i/nagios_sql-0.5.1/setup.cfg
Running nagios_sql-0.5.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-AjEE1i/nagios_sql-0.5.1/egg-dist-tmp-blqX8e
Traceback (most recent call last):
  File "/usr/bin/easy_install", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.6/site-packages/setuptools/command/easy_install.py", line 2279, in main
    **kw
  File "/usr/lib64/python2.6/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/usr/lib64/python2.6/distutils/dist.py", line 975, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python2.6/distutils/dist.py", line 995, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.6/site-packages/setuptools/command/easy_install.py", line 411, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/lib/python2.6/site-packages/setuptools/command/easy_install.py", line 672, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/lib/python2.6/site-packages/setuptools/command/easy_install.py", line 698, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/lib/python2.6/site-packages/setuptools/command/easy_install.py", line 879, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/lib/python2.6/site-packages/setuptools/command/easy_install.py", line 1118, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/lib/python2.6/site-packages/setuptools/command/easy_install.py", line 1104, in run_setup
    run_setup(setup_script, args)
  File "/usr/lib/python2.6/site-packages/setuptools/sandbox.py", line 257, in run_setup
    raise
  File "/usr/lib64/python2.6/contextlib.py", line 34, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python2.6/site-packages/setuptools/sandbox.py", line 199, in setup_context
    yield
  File "/usr/lib64/python2.6/contextlib.py", line 34, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python2.6/site-packages/setuptools/sandbox.py", line 170, in save_modules
    saved_exc.resume()
  File "/usr/lib/python2.6/site-packages/setuptools/sandbox.py", line 145, in resume
    six.reraise(type, exc, self._tb)
  File "/usr/lib/python2.6/site-packages/setuptools/sandbox.py", line 158, in save_modules
    yield saved
  File "/usr/lib/python2.6/site-packages/setuptools/sandbox.py", line 199, in setup_context
    yield
  File "/usr/lib/python2.6/site-packages/setuptools/sandbox.py", line 254, in run_setup
    _execfile(setup_script, ns)
  File "/usr/lib/python2.6/site-packages/setuptools/sandbox.py", line 49, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-AjEE1i/nagios_sql-0.5.1/setup.py", line 17, in <module>
  File "<string>", line 5
    __version__ = '0.5.1'
                         ^
SyntaxError: invalid syntax

**Comment by pablodav** [comment]
Great to see it working on python3, and good to see it working on python3.6! (haven't tested it yet). 

Python 2.6 life ended on 2013 so seems to be no reason to support such older version, but redhat seems to be backporting some code yet on centos6: 

https://www.centos.org/forums/viewtopic.php?t=60514

I will close this issue as looks you have successfully installed the software. 

Feel free to report any other issue.
